export * from "./Auth/auth.service";
export * from "./Banner/banner.service";
export * from "./Content/content.service";
export * from "./Feedback/feedback.service";
export * from "./General/general.service";
// export * from "./Message/message.service";
export * from "./Notice/notice.service";
export * from "./Research/research.service";
export * from "./Surveytip/surveytip.service";
export * from "./User/user.service";
