export const CORS_ORIGINS = ["*"];

export const MONGODB_FEEDBACK_CONNECTION = "MONGODB_FEEDBACK_CONNECTION";
export const MONGODB_NOTICE_CONNECTION = "MONGODB_NOTICE_CONNECTION";
export const MONGODB_RESEARCH_CONNECTION = "MONGODB_RESEARCH_CONNECTION";
export const MONGODB_USER_CONNECTION = "MONGODB_USER_CONNETION";
export const MONGODB_VOTE_CONNECTION = "MONGODB_VOTE_CONNECTION";
