export * from "./Auth/auth.controller";
export * from "./Banner/banner.controller";
export * from "./Content/content.controller";
export * from "./Feedback/feedback.controller";
export * from "./General/general.controller";
// export * from "./Message/message.controller";
export * from "./Notice/notice.controller";
export * from "./Research/research.controller";
export * from "./Surveytip/surveytip.controller";
export * from "./User/user.controller";
