export enum ResearchEstimatedTime {
  UNDER_ONE_MIN = "UNDER_ONE_MIN",
  ONE_TO_TWO_MIN = "ONE_TO_TWO_MIN",
  TWO_TO_THREE_MIN = "TWO_TO_THREE_MIN",
  THREE_TO_FIVE_MIN = "THREE_TO_FIVE_MIN",
  FIVE_TO_SEVEN_MIN = "FIVE_TO_SEVEN_MIN",
  SEVEN_TO_TEN_MIN = "SEVEN_TO_TEN_MIN",
  OVER_TEN_MIN = "OVER_TEN_MIN",
}
