#참고: https://teichae.tistory.com/entry/Github-Actions%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-Docker-Image-Build-%EB%B0%8F-Push

name: CI-docker

on:
  workflow_dispatch:

jobs:
  # build라는 이름의 job을 정의합니다.
  build:
    # job이 동작할 환경을 설정합니다: 20.04 버전 우분투
    runs-on: ubuntu-20.04

    # job이 수행할 실제 동작들을 설정합니다. 순차적으로 실행됩니다.
    steps:
      # 레포지토리 환경을 runner로 복사합니다.
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set docker metadata
        id: docker_metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: pickpleresearch/server-nestjs
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{steps.docker_metadata.outputs.tags}}
          labels: ${{steps.docker_metadata.outputs.labels}}
